### ISSUE TITLE
Error if submodule and this action added in the same PR

### ISSUE THREAD

**Issue by lydell** [jtmullen/submodule-branch-check-action#14]
If I add a submodule and this action in the same PR, the check fails since it tries to check out the submodule on master/main as well to calculate how the submodule changed:

```
__Line:66__Error: Could not checkout submodule hash referenced by master (is it pushed to remote?)
```

A workaround is to first add the submodule, then add the check in a separate PR.

It would be nice if the action could say something like “new submodule” in this case. Or at least document this gotcha.

**Comment by jtmullen** [comment]
Thanks for the issue, I agree that situation should be handled better for setup with new submodules. I think I will switch that error to a warning if the submodule is new. Then it won't fail and the rest of the checks applicable can be run.

**Comment by jtmullen** [comment]
The latest release now includes handling for this. If you have to set it up again in the future it should go smoother @lydell, thanks!

**Comment by lydell** [comment]
Awesome, thank you! 🎉
