### ISSUE TITLE
Code is on previous commit after action is complete

### ISSUE THREAD

**Issue by thejerrybao** [jtmullen/submodule-branch-check-action#21]
After the action completes its check, the repository is not checked out to the commit merged on non-PR branches. It should at the very end of the check, checkout back to the commit merged. Our use case is after the check is complete, we build a Java JAR from the branch merged and package it into a Docker container.

**Comment by jtmullen** [comment]
Hi @thejerrybao, thanks for this issue - I really should have had it work this way from the get go.  This is now resolved in the latest release!

**Comment by thejerrybao** [comment]
Thanks so much for the fix @jtmullen!
