### ISSUE TITLE
Make progression check configurable

### ISSUE THREAD

**Issue by nmote** [jtmullen/submodule-branch-check-action#26]
It looks like this check cannot be turned off: https://github.com/jtmullen/submodule-branch-check-action/blob/main/entrypoint.sh#L203-L216

For my use case, I would prefer not to have this check run. Ideally, the submodule would always point to the desired branch. However, if it does end up pointing to another branch, the progression check will fail on the PR to update it back to the desired branch.

**Comment by jtmullen** [comment]
Hi @nmote, yes that check is currently always run - it was the primary focus when I first wrote this action. But it would be relatively simple to add an input to disable it. I should be able to do that in the next week or so

**Comment by nmote** [comment]
That would be great! Looking forward to it.

**Comment by jtmullen** [comment]
Just released a new version that I think adds what you were looking for -- hopefully that works for you!

**Comment by nmote** [comment]
Looks good, thanks so much!
