### ISSUE TITLE
Not working with my submodule

### ISSUE THREAD

**Issue by matinlotfali** [jtmullen/submodule-branch-check-action#29]
Hi. I am trying to use your GitHub action and my submodule branch is already on the HEAD of the `develop` branch.
But the action fails.

Here is the log: https://github.com/MistySOM/rzv2l/actions/runs/4397568750/jobs/7700791855
Here is the YAML file: https://github.com/MistySOM/rzv2l/blob/check-submodule/.github/workflows/check-submodule.yml
Here is the pull request that I am trying to run the GitHub action on: https://github.com/MistySOM/rzv2l/pull/13

**Comment by jtmullen** [comment]
Hi @matinlotfali, just took a look into this. It appears to be correctly failing. You have configured it to require that the commit on the submodule be a part of a branch with the same name as the `${{ github.base_ref }}`, in your linked PR this is the branch `develop`. [Github does not return any results](https://github.com/MistySOM/meta-mistysom/branches/all?query=develop) for a branch called `develop` on your submodule repo. So there is no way for the commit to be on a branch that does not exist.

**Comment by matinlotfali** [comment]
@jtmullen thank you for your time you spent to look at this.
But the submodule does have the `develop` branch. See here:
https://github.com/MistySOM/meta-mistysom/tree/develop

**Comment by jtmullen** [comment]
Interesting, not sure why I wasn't seeing that before. In any case I seem to have located the bug, I'll roll out a new version later today and let you know. 

Bug is related to this [git setting](https://stackoverflow.com/questions/11623862/fetch-in-git-doesnt-get-all-branches#comment15394706_11623862). Seems like I should have run into this before, but apparently not so thanks for bringing it to my attention!

**Comment by jtmullen** [comment]
Hi @matinlotfali this is now fixed in [`v1.2.1`](https://github.com/jtmullen/submodule-branch-check-action/releases/tag/v1.2.1) so hopefully everything will work for you now. I will close this issue, let me know if anything else comes up

**Comment by matinlotfali** [comment]
Big thanks to @jtmullen for fixing this!
